/* Database schema to keep the structure of entire database. */

CREATE TABLE animals (
  id integer,
  name varchar(100),
  date_of_birth date,
  escape_attempts integer,
  neutered boolean,
  weight_kg real
);
ALTER TABLE animals ADD COLUMN species varchar(255);
ALTER TABLE animals ALTER COLUMN id SET NOT NULL;
ALTER TABLE animals ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
ALTER TABLE animals ADD PRIMARY KEY (id);

CREATE TABLE owners (
  id integer NOT NULL GENERATED ALWAYS AS IDENTITY,
  full_name varchar(255),
  age integer,
  PRIMARY KEY (id)
);

CREATE TABLE species (
  id integer NOT NULL GENERATED ALWAYS AS IDENTITY,
  name varchar(255),
  PRIMARY KEY (id)
);

ALTER TABLE animals DROP COLUMN species;
ALTER TABLE animals ADD COLUMN species_id INTEGER;
ALTER TABLE animals ADD COLUMN owner_id INTEGER;
ALTER TABLE animals 
ADD CONSTRAINT fk_species FOREIGN KEY (species_id) REFERENCES species(id);
ALTER TABLE animals 
ADD CONSTRAINT fk_owners FOREIGN KEY (owner_id) REFERENCES owners(id);
