/* Database schema to keep the structure of entire database. */

CREATE TABLE animals (
  id integer,
  name varchar(100),
  date_of_birth date,
  escape_attempts integer,
  neutered boolean,
  weight_kg real
);
ALTER TABLE animals ADD COLUMN species varchar(255);
ALTER TABLE animals ALTER COLUMN id SET NOT NULL;
ALTER TABLE animals ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
ALTER TABLE animals ADD PRIMARY KEY (id);
